version: '3'
services:
  __project_key___app:
    expose:
      - "80"
      - "443"
    environment:
      VIRTUAL_HOST=${HOST_NAMES}
      LETSENCRYPT_HOST=${HOST_NAMES}
      BASE_URL: ${BASE_LIVE_URL}
      DEBUG_ON: 0

networks:
  default:
    external:
      name: webproxy

